In [1]:
import numpy as np
import pandas as pd
import scipy as sp

In [2]:
#A=np.matrix([[11,24,32],[12,4,6],[3,7,2],[5,4,9]])
A=pd.read_csv("/home/sumit/sumit/downlod 1/train.csv")
B=A.dot(A.T)
B

0             1             2             3             4    \
0    1.262492e+06  1.245798e+06  1.235223e+06  1.244936e+06  1.261810e+06   
1    1.245798e+06  1.231109e+06  1.221350e+06  1.229722e+06  1.245614e+06   
2    1.235223e+06  1.221350e+06  1.212740e+06  1.219832e+06  1.234914e+06   
3    1.244936e+06  1.229722e+06  1.219832e+06  1.228512e+06  1.244612e+06   
4    1.261810e+06  1.245614e+06  1.234914e+06  1.244612e+06  1.261489e+06   
5    1.262679e+06  1.246461e+06  1.236142e+06  1.245482e+06  1.262163e+06   
6    1.241545e+06  1.227156e+06  1.217367e+06  1.225656e+06  1.241397e+06   
7    1.264882e+06  1.249061e+06  1.238964e+06  1.247965e+06  1.264472e+06   
8    1.233626e+06  1.220428e+06  1.212028e+06  1.218693e+06  1.233464e+06   
9    1.270450e+06  1.253697e+06  1.243347e+06  1.252841e+06  1.269681e+06   
10   1.235744e+06  1.221735e+06  1.212221e+06  1.220171e+06  1.235681e+06   
11   1.248590e+06  1.233883e+06  1.224887e+06  1.232567e+06  1.248154e+06   
12   1.235325e+06  1.221808e+06  1.212623e+06  1.220120e+06  1.235376e+06   
13   1.259752e+06  1.243143e+06  1.232891e+06  1.242294e+06  1.258986e+06   
14   1.256718e+06  1.241426e+06  1.232021e+06  1.240234e+06  1.256207e+06   
15   1.258165e+06  1.243530e+06  1.234111e+06  1.242076e+06  1.257821e+06   
16   1.251818e+06  1.236655e+06  1.227644e+06  1.235466e+06  1.251175e+06   
17   1.267506e+06  1.251323e+06  1.240914e+06  1.250293e+06  1.267017e+06   
18   1.265467e+06  1.249370e+06  1.239512e+06  1.248364e+06  1.264794e+06   
19   1.233733e+06  1.219203e+06  1.210658e+06  1.217936e+06  1.233187e+06   
20   1.258657e+06  1.243010e+06  1.232958e+06  1.241853e+06  1.258184e+06   
21   1.228446e+06  1.215057e+06  1.206309e+06  1.213395e+06  1.228374e+06   
22   1.243724e+06  1.229424e+06  1.219793e+06  1.227907e+06  1.243584e+06   
23   1.273011e+06  1.256527e+06  1.245956e+06  1.255567e+06  1.272496e+06   
24   1.263226e+06  1.247306e+06  1.237291e+06  1.246251e+06  1.262722e+06   
25   1.279427e+06  1.262571e+06  1.252292e+06  1.261722e+06  1.278624e+06   
26   1.242840e+06  1.228540e+06  1.218897e+06  1.227047e+06  1.242770e+06   
27   1.272624e+06  1.255727e+06  1.245019e+06  1.254874e+06  1.271917e+06   
28   1.248298e+06  1.233517e+06  1.224018e+06  1.232158e+06  1.247937e+06   
29   1.240614e+06  1.227089e+06  1.218243e+06  1.225408e+06  1.240542e+06   
..            ...           ...           ...           ...           ...   
269  1.234202e+06  1.219711e+06  1.210323e+06  1.218363e+06  1.234010e+06   
270  1.253387e+06  1.238872e+06  1.228956e+06  1.237374e+06  1.253328e+06   
271  1.235413e+06  1.221550e+06  1.212032e+06  1.219938e+06  1.235410e+06   
272  1.259525e+06  1.244457e+06  1.234638e+06  1.243128e+06  1.259223e+06   
273  1.238605e+06  1.225251e+06  1.216644e+06  1.223528e+06  1.238459e+06   
274  1.235107e+06  1.221449e+06  1.212570e+06  1.219792e+06  1.234843e+06   
275  1.238715e+06  1.224847e+06  1.215121e+06  1.223191e+06  1.238754e+06   
276  1.272327e+06  1.255875e+06  1.246104e+06  1.254955e+06  1.271456e+06   
277  1.234995e+06  1.221346e+06  1.212044e+06  1.219696e+06  1.235042e+06   
278  1.229286e+06  1.215237e+06  1.206447e+06  1.213816e+06  1.229048e+06   
279  1.261537e+06  1.245323e+06  1.235522e+06  1.244367e+06  1.260750e+06   
280  1.249924e+06  1.235159e+06  1.225871e+06  1.233819e+06  1.249533e+06   
281  1.253195e+06  1.237153e+06  1.226812e+06  1.236163e+06  1.252774e+06   
282  1.273823e+06  1.257160e+06  1.246615e+06  1.256247e+06  1.273187e+06   
283  1.262797e+06  1.247154e+06  1.237226e+06  1.246028e+06  1.262413e+06   
284  1.239212e+06  1.224858e+06  1.214691e+06  1.223331e+06  1.239239e+06   
285  1.259852e+06  1.243197e+06  1.232433e+06  1.242309e+06  1.259229e+06   
286  1.261098e+06  1.245587e+06  1.235470e+06  1.244410e+06  1.260842e+06   
287  1.244935e+06  1.231244e+06  1.222248e+06  1.229585e+06  1.244848e+06   
288  1.268463e+06  1.252188e+06  1.242182e+06  1.251216e+06  1.267776e+06   
289  1.237

In [3]:
sig_vec_u=np.linalg.eig(B)
sig_vec_u

(array([ 3.70888625e+08+0.00000000e+00j,  1.41016234e+05+0.00000000e+00j,
         5.04348837e+04+0.00000000e+00j,  6.61114816e+03+0.00000000e+00j,
         1.34836256e+03+0.00000000e+00j,  1.63433226e-08+6.63638041e-09j,
         1.63433226e-08-6.63638041e-09j,  1.57306074e-08+0.00000000e+00j,
         1.41624088e-08+3.12190609e-09j,  1.41624088e-08-3.12190609e-09j,
         9.70306407e-09+1.13632313e-08j,  9.70306407e-09-1.13632313e-08j,
        -9.10985148e-09+1.39265117e-08j, -9.10985148e-09-1.39265117e-08j,
        -1.04563577e-08+1.18676801e-08j, -1.04563577e-08-1.18676801e-08j,
        -1.39960491e-08+5.86732560e-09j, -1.39960491e-08-5.86732560e-09j,
        -1.11261940e-08+9.07837974e-09j, -1.11261940e-08-9.07837974e-09j,
        -1.35049010e-08+0.00000000e+00j,  6.19727749e-09+1.26166826e-08j,
         6.19727749e-09-1.26166826e-08j, -5.50646460e-09+1.26111838e-08j,
        -5.50646460e-09-1.26111838e-08j,  2.22713339e-09+1.31998698e-08j,
         2.22713339e-09-1.31998698e-08

In [4]:
idx_u=sig_vec_u[0].argsort()[-1::-1]
idx_u

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  31,
        32,  33,  34,  21,  22,  35,  36,  54,  55,  58,  59,  52,  53,
        64,  65,  98,  99,  56,  57,  92,  93,  62,  63, 119, 130, 131,
       115, 116, 144, 145, 142, 143, 117, 118,  60,  61,  77,  78, 113,
       114, 184, 185, 188, 189, 100, 101, 190, 191, 186, 187, 152, 153,
       210, 211, 218,  25,  26, 170, 171,  85,  86, 158, 159, 212, 213,
       134, 135, 243, 244, 241, 242,  81,  82, 227, 228, 198, 199, 166,
       167, 269, 102, 103, 202, 203, 245, 246, 140, 141, 278, 279, 126,
       127, 288, 249, 250, 223, 224, 280, 281, 239, 240,  39,  40, 291,
        79,  80, 263, 264, 192, 193, 132, 133, 124, 125, 289, 290, 270,
       271, 253, 254, 225, 226, 168, 169, 182, 183, 284, 285, 294, 295,
       296, 297, 235, 236, 251, 252, 146, 147, 276, 277, 200, 201, 120,
       121, 247, 248, 160, 161, 292, 293, 267, 268, 286, 287,  27,  28,
       298, 231, 232, 162, 163,  66,  67, 128, 129, 265, 266, 28

In [5]:
sig_u=sig_vec_u[0][idx_u]
sig_u

array([ 3.70888625e+08+0.00000000e+00j,  1.41016234e+05+0.00000000e+00j,
        5.04348837e+04+0.00000000e+00j,  6.61114816e+03+0.00000000e+00j,
        1.34836256e+03+0.00000000e+00j,  1.63433226e-08+6.63638041e-09j,
        1.63433226e-08-6.63638041e-09j,  1.57306074e-08+0.00000000e+00j,
        1.41624088e-08+3.12190609e-09j,  1.41624088e-08-3.12190609e-09j,
        9.70306407e-09+1.13632313e-08j,  9.70306407e-09-1.13632313e-08j,
        9.44294605e-09+1.50642909e-09j,  9.44294605e-09-1.50642909e-09j,
        6.70215934e-09+5.91598466e-09j,  6.70215934e-09-5.91598466e-09j,
        6.19727749e-09+1.26166826e-08j,  6.19727749e-09-1.26166826e-08j,
        5.07167111e-09+3.55031804e-10j,  5.07167111e-09-3.55031804e-10j,
        4.61048123e-09+1.09947069e-09j,  4.61048123e-09-1.09947069e-09j,
        4.46588736e-09+3.88297120e-10j,  4.46588736e-09-3.88297120e-10j,
        4.27685209e-09+2.01762112e-09j,  4.27685209e-09-2.01762112e-09j,
        4.19100521e-09+1.03825642e-09j,  4.19100521

In [6]:
sigma_u=np.diag(sig_u)
sigma_u

array([[ 3.70888625e+08+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j, ...,
         0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j],
       [ 0.00000000e+00+0.0000000e+00j,  1.41016234e+05+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j, ...,
         0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j],
       [ 0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         5.04348837e+04+0.0000000e+00j, ...,
         0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j],
       ...,
       [ 0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j, ...,
        -1.35049010e-08+0.0000000e+00j,  0.00000000e+00+0.0000000e+00j,
         0.00000000e+00+0.0000000e+00j],
       [ 0.00000000e+00+0.0000000e+00j,  0.00000000e+00+0.0000000e+0

In [7]:
sigma_u=np.sqrt(sigma_u)
sigma_u

array([[1.92584689e+04+0.j        , 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , ..., 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , 0.00000000e+00+0.j        ],
       [0.00000000e+00+0.j        , 3.75521284e+02+0.j        ,
        0.00000000e+00+0.j        , ..., 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , 0.00000000e+00+0.j        ],
       [0.00000000e+00+0.j        , 0.00000000e+00+0.j        ,
        2.24577122e+02+0.j        , ..., 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , 0.00000000e+00+0.j        ],
       ...,
       [0.00000000e+00+0.j        , 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , ..., 0.00000000e+00+0.00011621j,
        0.00000000e+00+0.j        , 0.00000000e+00+0.j        ],
       [0.00000000e+00+0.j        , 0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        , ..., 0.00000000e+00+0.j        ,
        2.42907409e-05+0.00012077j, 0.00000000e+00+0.j        ]

In [8]:
u=sig_vec_u[1][idx_u]
u

array([[-5.83142831e-02+0.j        ,  9.30501640e-02+0.j        ,
         1.92614394e-02+0.j        , ..., -5.09683731e-02+0.05850167j,
        -5.09683731e-02-0.05850167j,  2.94994406e-02+0.j        ],
       [-5.76116827e-02+0.j        , -1.90681452e-02+0.j        ,
         2.59694641e-02+0.j        , ..., -7.42102971e-04+0.0074966j ,
        -7.42102971e-04-0.0074966j ,  2.69075045e-05+0.j        ],
       [-5.71565565e-02+0.j        , -6.57473151e-02+0.j        ,
        -9.70649266e-02+0.j        , ...,  4.88024888e-03+0.00302505j,
         4.88024888e-03-0.00302505j,  3.36929189e-02+0.j        ],
       ...,
       [-5.81765902e-02+0.j        ,  2.92217155e-02+0.j        ,
         6.09400216e-03+0.j        , ...,  5.26123419e-02+0.00773525j,
         5.26123419e-02-0.00773525j,  3.41861107e-02+0.j        ],
       [-5.78834395e-02+0.j        ,  2.16379293e-03+0.j        ,
        -1.24766375e-01+0.j        , ...,  8.74017742e-03+0.01759262j,
         8.74017742e-03-0.01759262j

In [9]:
#A=np.matrix([[11,24,32],[12,4,6],[3,7,2],[5,4,9]])
C=A.T.dot(A)
C

AT             V            AP            RH            PE
AT  1.361048e+05  3.473680e+05  6.022641e+06  4.082124e+05  2.663663e+06
V   3.473680e+05  9.287958e+05  1.641463e+07  1.147586e+06  7.300578e+06
AP  6.022641e+06  1.641463e+07  3.067549e+08  2.174002e+07  1.374456e+08
RH  4.082124e+05  1.147586e+06  2.174002e+07  1.606844e+06  9.771849e+06
PE  2.663663e+06  7.300578e+06  1.374456e+08  9.771849e+06  6.166136e+07

In [10]:
sig_vec_v=np.linalg.eig(C)
sig_vec_v

(array([3.70888625e+08, 1.41016234e+05, 5.04348837e+04, 1.34836256e+03,
        6.61114816e+03]),
 array([[-0.0178177 ,  0.34599966, -0.03802039, -0.91480706, -0.20408148],
        [-0.04860936,  0.54294762, -0.37713938,  0.05539939,  0.74668723],
        [-0.90942513,  0.25857858, -0.02351303,  0.17722593, -0.27225201],
        [-0.06449439, -0.41012039, -0.89327686, -0.08304835, -0.15100057],
        [-0.40756112, -0.59197171,  0.24046608, -0.34893106,  0.55125911]]))

In [11]:
idx_v=sig_vec_v[0].argsort()[-1::-1]
idx_v

array([0, 1, 2, 4, 3])

In [12]:
sig_v=sig_vec_v[0][idx_v]
sig_v

array([3.70888625e+08, 1.41016234e+05, 5.04348837e+04, 6.61114816e+03,
       1.34836256e+03])

In [13]:
sigma_v=np.diag(sig_v)
sigma_v

array([[3.70888625e+08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.41016234e+05, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.04348837e+04, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.61114816e+03,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.34836256e+03]])

In [14]:
sigma_v=np.sqrt(sigma_v)
sigma_v

array([[19258.46892768,     0.        ,     0.        ,     0.        ,
            0.        ],
       [    0.        ,   375.52128356,     0.        ,     0.        ,
            0.        ],
       [    0.        ,     0.        ,   224.577122  ,     0.        ,
            0.        ],
       [    0.        ,     0.        ,     0.        ,    81.30896725,
            0.        ],
       [    0.        ,     0.        ,     0.        ,     0.        ,
           36.72005666]])

In [15]:
v=sig_vec_v[1][idx_v]
v

array([[-0.0178177 ,  0.34599966, -0.03802039, -0.91480706, -0.20408148],
       [-0.04860936,  0.54294762, -0.37713938,  0.05539939,  0.74668723],
       [-0.90942513,  0.25857858, -0.02351303,  0.17722593, -0.27225201],
       [-0.40756112, -0.59197171,  0.24046608, -0.34893106,  0.55125911],
       [-0.06449439, -0.41012039, -0.89327686, -0.08304835, -0.15100057]])

In [16]:
sigma_v.shape

(5, 5)

In [17]:
sigma_u.shape

(299, 299)

In [18]:
u.shape

(299, 299)

In [19]:
v.shape

(5, 5)

In [20]:
col=min(u.shape[0],v.shape[0])

In [21]:
sigma=sigma_u[:,0:col]
sigma

array([[19258.46892768+0.j,     0.        +0.j,     0.        +0.j,
            0.        +0.j,     0.        +0.j],
       [    0.        +0.j,   375.52128356+0.j,     0.        +0.j,
            0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j,   224.577122  +0.j,
            0.        +0.j,     0.        +0.j],
       ...,
       [    0.        +0.j,     0.        +0.j,     0.        +0.j,
            0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j,     0.        +0.j,
            0.        +0.j,     0.        +0.j],
       [    0.        +0.j,     0.        +0.j,     0.        +0.j,
            0.        +0.j,     0.        +0.j]])

In [22]:
u=np.linalg.qr(u)

In [23]:
u[0]

array([[-0.05831428+0.j        ,  0.09305016+0.j        ,
         0.01926144+0.j        , ..., -0.040601  -0.00071427j,
         0.02704957-0.03043832j,  0.01036173-0.00396868j],
       [-0.05761168+0.j        , -0.01906815+0.j        ,
         0.02596946+0.j        , ...,  0.02968797-0.05211321j,
         0.01755258-0.09875664j,  0.01164892-0.0044617j ],
       [-0.05715656+0.j        , -0.06574732+0.j        ,
        -0.09706493+0.j        , ..., -0.11221903+0.02295471j,
         0.05708283-0.02681618j,  0.01268925-0.00486016j],
       ...,
       [-0.05817659+0.j        ,  0.02922172+0.j        ,
         0.006094  +0.j        , ...,  0.00308008-0.00262893j,
        -0.00014905-0.00385959j,  0.09554043-0.0365933j ],
       [-0.05788344+0.j        ,  0.00216379+0.j        ,
        -0.12476637+0.j        , ...,  0.0181425 -0.00478192j,
        -0.00846913+0.00187348j, -0.04133281+0.01583104j],
       [-0.05856805+0.j        ,  0.05880246+0.j        ,
         0.02155606+0.j       

In [24]:
v=np.linalg.qr(v)

In [25]:
v[0]

array([[-0.0178177 , -0.34599966, -0.03802039,  0.91480706, -0.20408148],
       [-0.04860936, -0.54294762, -0.37713938, -0.05539939,  0.74668723],
       [-0.90942513, -0.25857858, -0.02351303, -0.17722593, -0.27225201],
       [-0.40756112,  0.59197171,  0.24046608,  0.34893106,  0.55125911],
       [-0.06449439,  0.41012039, -0.89327686,  0.08304835, -0.15100057]])

In [26]:
A_p=u[0].dot(sigma).dot(v[0].T)
A_p

array([[  11.88379642+0.j,   34.73103065+0.j, 1010.96548699+0.j,
         481.86005513+0.j,   83.09203865+0.j],
       [  20.03616245+0.j,   56.35646866+0.j, 1010.85733124+0.j,
         449.12635296+0.j,   63.11947236+0.j],
       [  26.49901819+0.j,   76.8537758 +0.j, 1007.75907042+0.j,
         429.16217509+0.j,   79.8296213 +0.j],
       ...,
       [  19.90072095+0.j,   47.35829472+0.j, 1015.47918592+0.j,
         464.55509466+0.j,   75.95278878+0.j],
       [  21.15475919+0.j,   64.06085314+0.j, 1014.22274215+0.j,
         448.07456289+0.j,   97.34359175+0.j],
       [  12.40616948+0.j,   40.05788695+0.j, 1020.32141982+0.j,
         473.17595536+0.j,   77.65994323+0.j]])

In [27]:
err=A-A_p

In [28]:
err

AT                         V  \
0    (-3.5437964210820763+0j)    (6.038969345930312+0j)   
1     (3.6038375484874763+0j)   (2.1335313447757827+0j)   
2     (3.2409818092500515+0j)  (-19.953775795142327+0j)   
3      (4.120958471596518+0j)  (-0.6977504282722364+0j)   
4      (7.871587438596691+0j)    (6.364283154455954+0j)   
5      (6.027737937649959+0j)  (-3.0984377841012645+0j)   
6     (-8.573705528655502+0j)    (16.17302500152801+0j)   
7      (4.698869948425758+0j)   (-4.343091654832293+0j)   
8     (-4.715432813202874+0j)  (-12.025613776602526+0j)   
9    (-6.3769750647412256+0j)  (0.20358310667680257+0j)   
10     (1.178270472684698+0j)    (5.952022519955975+0j)   
11    (3.5712086714378373+0j)   (-20.34054303638427+0j)   
12    (13.884995951735684+0j)   (20.875644975656428+0j)   
13   (-2.1275141877092114+0j)   (-1.591765709655796+0j)   
14   (-15.144490084584383+0j)   (-32.76722696439082+0j)   
15   (-12.334482641936866+0j)  (-12.912647660566847+0j)   
16    (-9.303104033562807+0j)   (-33.42490895550594+0j)   
17    (-16.74935640540093+0j)  (-15.405998779205312+0j)   
18   (-14.079417619023749+0j)  (-17.405615182490344+0j)   
19    (0.7686402516495043+0j)   (-5.497424913868542+0j)   
20   (-14.493843741579271+0j)  (-19.739942794750405+0j)   
21    (28.112317671380453+0j)   (24.195773220836216+0j)   
22     (22.97344856244675+0j)   (31.070349171302013+0j)   
23   (-23.287176980368752+0j)  (-20.618132399208754+0j)   
24    (-0.803110132928115+0j)   (-15.87758816436758+0j)   
25   (-18.906570870707352+0j)   (-17.07629458592151+0j)   
26    (-6.288683314739934+0j)  (-17.632713368610467+0j)   
27    (-25.47740945089279+0j)   (-19.40291027230962+0j)   
28   (-15.153986603014467+0j)  (-18.523176027548843+0j)   
29    (17.952365935693777+0j)    (31.73811735901645+0j)   
..                        ...                       ...   
269   (0.5735233900949979+0j)  (-17.177704874245592+0j)   
270   (1.4372761280085022+0j)   (16.635672482490648+0j)   
271  (-0.5315950743649225+0j)    (2.196113497801207+0j)   
272   (6.5278314056953235+0j)   (19.130041971014734+0j)   
273    (4.919565270295664+0j)    (5.723744861371458+0j)   
274   (20.071226538167352+0j)    (25.66045045625362+0j)   
275   (18.767348128718037+0j)    (25.12685656442501+0j)   
276  (-16.934198341401185+0j)   (-5.310148401319495+0j)   
277    (17.06804356696435+0j)   (23.472101610924874+0j)   
278   (3.9086146240684805+0j)   (-2.023245548269003+0j)   
279   (-14.36390984106102+0j)   (-31.17791335865747+0j)   
280   (13.456660993307281+0j)   (12.762905122498715+0j)   
281   (3.5786271525626363+0j)  (-3.8975896467411033+0j)   
282   (-4.872982930836171+0j)  (-17.788167972906805+0j)   
283  (-10.421738439512849+0j)  (-23.148761417814114+0j)   
284   (-9.296326659970507+0j)   (0.5418485872484666+0j)   
285  (-19.826476867119837+0j)   (1.8784190195805905+0j)   
286    (7.164624972130868+0j)    (9.090137441955015+0j)   
287   (18.913649623643373+0j)    (20.68378512339323+0j)   
288  (-17.553380851018147+0j)   (-28.40292438094427+0j)   
289    (17.84369441624145+0j)    (35.94635033058976+0j)   
290  (-1.3149750154965822+0j)  (-1.8504809272056661+0j)   
291   (11.907819715031783+0j)   (21.359363781916926+0j)   
292    (9.887406183222993+0j)   (7.3121183271404036+0j)   
293   (0.9285231970651537+0j)   (16.326980123675348+0j)   
294     (9.57294280436871+0j)   (27.438509642843975+0j)   
295  (-14.464408916042753+0j)   (-33.65184739008423+0j)   
296   (10.689279054414182+0j)   (22.681705281974743+0j)   
297   (-7.114759185193147+0j)  (-15.270853137433967+0j)   
298    (3.063830519385718+0j)    (4.842113054715632+0j)   

                             AP                        RH  \
0     (-0.12548698736759434+0j)   (-391.8500551253966+0j)   
1       (0.5426687609011651+0j)   (-374.9263529612505+0j)   
2      (-0.6090704213355593+0j)   (-387.2521750901152+0j)   
3      (0.46316741315695253+0j)  (-378.34855754622083+0j)   
4        (1.270789440367139+0j)  (-375.58909343767266+0j)   
5 

In [35]:
err=(np.linalg.norm(A-A_p))/A.shape[0]
err

31.32647134742744